FROM python:3.11

ENV TZ=Europe/Berlin
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -q -qq update && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends --fix-missing \
    git curl ca-certificates \
    gcc cmake pkg-config libcairo2-dev libgirepository-2.0-dev python3-dev \
    libgstreamer1.0-dev gstreamer1.0-tools \
    gstreamer1.0-pulseaudio gstreamer1.0-alsa alsa-utils \
    python3-gst-1.0 \
    ffmpeg sox \
    && rm -rf /var/lib/apt/lists/*

# Download the latest uv installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh
# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh
# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

WORKDIR /app
RUN uv venv
RUN uv pip install "torch>=2.8.0" "torchaudio<=2.8.0" "paho-mqtt>=2.1.0" "pyyaml>=6.0"